/* Offline precache for the PSKT receiver.
 *
 * The manifest below is generated by tools/build-web.mjs: every cached URL carries the
 * SHA-256 of the bytes that were on disk at build time. tools/check-dist.mjs recomputes
 * those hashes from the built files and fails the build if the manifest and the artifacts
 * disagree -- that is the "SW 清单哈希与产物一致" criterion, checked where it can actually
 * be checked (against files), rather than by asking a browser to trust itself.
 *
 * The placeholder tokens are replaced by the build; an un-built copy of this file will
 * contain the literals below and refuses to install, which is the correct outcome for a
 * source file that was never meant to be served.
 */
const BUILD_ID = '__PSKT_BUILD_ID__';
const MANIFEST = __PSKT_PRECACHE_MANIFEST__;
const CACHE = `pskt-${BUILD_ID}`;

self.addEventListener('install', (event) => {
  if (typeof MANIFEST !== 'object' || MANIFEST === null || !Array.isArray(MANIFEST.entries)) {
    // Refuse to install rather than cache "something". A half-registered SW is worse than
    // none because it silently serves a stale shell.
    self.skipWaiting();
    return;
  }
  event.waitUntil(
    caches
      .open(CACHE)
      .then((c) => Promise.all(MANIFEST.entries.map((e) => c.add(new Request(e.url, { cache: 'reload' })))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('pskt-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // Same-origin only. Anything else is not this app's business, and there is a CSP
  // (default-src 'self') that should make such a request impossible anyway.
  if (url.origin !== self.location.origin) return;
  event.respondWith(
    caches.match(req).then(
      (hit) =>
        hit ||
        fetch(req).catch(() => {
          // Offline and not precached: name the missing file instead of returning an
          // opaque error page that a user would read as "the app is broken".
          return new Response(`offline and not precached: ${url.pathname}`, { status: 504, headers: { 'content-type': 'text/plain' } });
        }),
    ),
  );
});
